import { MDXRemote } from "next-mdx-remote/rsc";
import React from "react";

import { loadBlogPost } from "@/helpers/file-helpers";
import COMPONENT_MAP from "@/helpers/mdx-components";

import styles from "./BlogPost.module.css";

export type BlogPostParams = {
  params: { postSlug: string };
};

async function BlogPost({ params }: BlogPostParams) {
  const { frontmatter, content } = await loadBlogPost(params.postSlug);
  const { title, chatGPTPrompt } = frontmatter;

  return (
    <main className={styles.wrapper}>
      <section className={styles.blogHero}>
        <h1 className={styles.blogTitle}>{title}</h1>
        <p className={styles.disclaimer}>
          Note: this post was <strong>generated by ChatGPT</strong> with the
          prompt {/* prettier-ignore */}
          &ldquo;{chatGPTPrompt}.&rdquo; The quality of this post is
          questionable at best.
        </p>
      </section>
      <section className={styles.content}>
        <MDXRemote source={content} components={COMPONENT_MAP} />
      </section>
      {/* TODO: add table of contents */}
    </main>
  );
}

export default BlogPost;
